<div align="left" style="background-color: #008080; padding: 20px 10px;">
<h3><b>IDEAS - Institute of Data Engineering, Analytics and Science Foundation</b></h3>
<p>Summer Internship Program 2026</p>
<hr style="width:100%;">
<h3><b>Project Title:</b> Exploratory data analysis with Coffee sales data and MNIST data clustering.</h3>
<h4>Project Notebook</h4>

<blockquote style="border-left: 4px solid #4285F4; padding-left: 15px;">
  <strong>Created by:</strong> Koulika Paul<br>
  <strong>Designation:</strong> Project Linked Associate Research Engineer in Statistics
</blockquote>
<hr style="width:100%;">
</div>

### Question 1: Import Libraries and Load Data (1 Mark)

Import the `pandas` library as `pd`. Then, download the data `Coffe_sales.csv` from https://drive.google.com/drive/folders/1gieHICVDBbUKMZiSF4YRQMAJic-w50JM?usp=sharing and load into a DataFrame named `coffee_data` and display its first 5 rows.

**Expected Output:** A table showing the first 5 rows of the coffee sales data.

In [ ]:
import pandas as pd


coffee_data = pd.read_csv("Coffe_sales (1).csv")


print(coffee_data.head())

   hour_of_day cash_type  money    coffee_name Time_of_Day Weekday Month_name  \
0           10      card   38.7          Latte     Morning     Fri        Mar   
1           12      card   38.7  Hot Chocolate   Afternoon     Fri        Mar   
2           12      card   38.7  Hot Chocolate   Afternoon     Fri        Mar   
3           13      card   28.9      Americano   Afternoon     Fri        Mar   
4           13      card   38.7          Latte   Afternoon     Fri        Mar   

   Weekdaysort  Monthsort        Date             Time  
0            5          3  2024-03-01  10:15:50.520000  
1            5          3  2024-03-01  12:19:22.539000  
2            5          3  2024-03-01  12:20:18.089000  
3            5          3  2024-03-01  13:46:33.006000  
4            5          3  2024-03-01  13:48:14.626000  


### Question 2: Initial Data Inspection (2 Marks)

Perform a basic inspection of the `coffee_data` DataFrame. Print the number of rows and columns, check for any duplicate rows, and find the total number of missing values in the entire dataset.

**Expected Output:** A printout of the shape, the number of duplicate rows, and the total number of missing values.

In [ ]:

print("Shape of dataset:", coffee_data.shape)

# Duplicate rows
print("Number of duplicate rows:", coffee_data.duplicated().sum())

# Missing values
print("Total missing values:", coffee_data.isnull().sum().sum())

Shape of dataset: (3547, 11)
Number of duplicate rows: 0
Total missing values: 0


### Question 3: Basic Statistics (1 Marks)

Generate and display the basic descriptive statistics for the numerical columns in the `coffee_data` DataFrame.

**Hint:** Use the `.describe()` method on your DataFrame.

**Expected Output:** A table showing count, mean, std, min, 25%, 50%, 75%, and max for the numerical columns.

In [ ]:
import pandas as pd

# Descriptive statistics
print(coffee_data.describe())

       hour_of_day        money  Weekdaysort    Monthsort
count  3547.000000  3547.000000  3547.000000  3547.000000
mean     14.185791    31.645216     3.845785     6.453905
std       4.234010     4.877754     1.971501     3.500754
min       6.000000    18.120000     1.000000     1.000000
25%      10.000000    27.920000     2.000000     3.000000
50%      14.000000    32.820000     4.000000     7.000000
75%      18.000000    35.760000     6.000000    10.000000
max      22.000000    38.700000     7.000000    12.000000


### Question 4: Data Type Conversion (1 Marks)

The 'Date' column is currently an object. Convert it to a datetime object. Then, create two new columns: 'Month' (containing the month number) and 'Year' (containing the year as an integer). Finally, display the data types of all columns.

**Expected Output:** A series listing each column and its updated data type.

In [ ]:
import pandas as pd


coffee_data['Date'] = pd.to_datetime(coffee_data['Date'])

# Create new columns
coffee_data['Month'] = coffee_data['Date'].dt.month
coffee_data['Year'] = coffee_data['Date'].dt.year

# Display data types
print(coffee_data.dtypes)

hour_of_day             int64
cash_type              object
money                 float64
coffee_name            object
Time_of_Day            object
Weekday                object
Month_name             object
Weekdaysort             int64
Monthsort               int64
Date           datetime64[ns]
Time                   object
Month                   int32
Year                    int32
dtype: object


### Question 5: Data Aggregation and Analysis (5 Marks)

Perform the following data analysis tasks:
1. **Average Sales per Year:** Calculate the average 'money' (sales) for each 'Year'. Group the data by the 'Year' column and then compute the mean of the 'money' column for each group.
2. **Maximum Sales by Month Name:** Find the maximum 'money' earned for each 'Month_name'. Display the result as a Pandas Series.
3. **Total Sales by Coffee Name:** Calculate the total 'money' (sum of sales) for each 'coffee_name'.
4. **Unique Coffee Types:** Determine how many unique types of coffee are present in the dataset. Print the unique coffee names as a list.
5. **Average Sales by Time of Day:** Find the average 'money' made during each 'Time_of_Day' (Morning, Afternoon, Night).

**Expected Output:** Display the appropriate results for each step (e.g. Pandas Series and list) clearly.

In [ ]:
avg_sales_per_year = coffee_data.groupby('Year')['money'].mean()
print(avg_sales_per_year)
max_sales_by_month = coffee_data.groupby('Month_name')['money'].max()
print(max_sales_by_month)
total_sales_by_coffee = coffee_data.groupby('coffee_name')['money'].sum()
print(total_sales_by_coffee)
unique_coffees = coffee_data['coffee_name'].unique()
print(list(unique_coffees))
print("Number of unique coffee types:", len(unique_coffees))
avg_sales_time = coffee_data.groupby('Time_of_Day')['money'].mean()
print(avg_sales_time)

Year
2024    31.737634
2025    31.390011
Name: money, dtype: float64
Month_name
Apr    38.70
Aug    32.82
Dec    35.76
Feb    35.76
Jan    35.76
Jul    37.72
Jun    37.72
Mar    38.70
May    37.72
Nov    35.76
Oct    35.76
Sep    35.76
Name: money, dtype: float64
coffee_name
Americano              14650.26
Americano with Milk    24751.12
Cappuccino             17439.14
Cocoa                   8521.16
Cortado                 7384.86
Espresso                2690.28
Hot Chocolate           9933.46
Latte                  26875.30
Name: money, dtype: float64
['Latte', 'Hot Chocolate', 'Americano', 'Americano with Milk', 'Cocoa', 'Cortado', 'Espresso', 'Cappuccino']
Number of unique coffee types: 8
Time_of_Day
Afternoon    31.643187
Morning      30.422693
Night        32.890904
Name: money, dtype: float64


### Question 6: Generate and Display Synthetic Data (3 Marks)

Create a new, synthetic DataFrame named `synthetic_df`. It should have two columns: 'date' and 'value'. The 'date' column should contain 100 dates starting from '2023-01-01'. The 'value' column should contain 100 random numbers. Display the entire synthetic DataFrame.

**Expected Output:** A 100x2 DataFrame with 'date' and 'value' columns.

In [ ]:
import pandas as pd
import numpy as np


dates = pd.date_range(start='2023-01-01', periods=100)


values = np.random.rand(100)   # random numbers between 0 and 1


synthetic_df = pd.DataFrame({
    'date': dates,
    'value': values
})

print(synthetic_df)

         date     value
0  2023-01-01  0.607867
1  2023-01-02  0.689576
2  2023-01-03  0.306925
3  2023-01-04  0.542596
4  2023-01-05  0.535694
..        ...       ...
95 2023-04-06  0.114935
96 2023-04-07  0.890144
97 2023-04-08  0.272200
98 2023-04-09  0.245204
99 2023-04-10  0.927531

[100 rows x 2 columns]


### Question 7: Load MNIST Data (4 Marks)

Load the MNIST dataset using `sklearn.datasets.load_digits`. Separate the dataset into features (`X`) and target labels (`y`).
Print the shape of the features and the target arrays.

**Expected Output:** The shape of `X` and `y`.

In [ ]:
from sklearn.datasets import load_digits

# Load dataset
digits = load_digits()


X = digits.data
y = digits.target

# Print shapes
print("Shape of X (features):", X.shape)
print("Shape of y (target):", y.shape)


Shape of X (features): (1797, 64)
Shape of y (target): (1797,)


### Question 8: K-Means Clustering (5 Marks)

Import `KMeans` from `sklearn.cluster`. Initialize and fit the K-Means clustering model on the MNIST features (`X`).
Since we know there are 10 digits (0-9), set the number of clusters to 10. Assign the cluster labels to a variable `kmeans_labels`.

**Expected Output:** A successfully fitted K-Means model and the cluster labels array.

In [ ]:
from sklearn.cluster import KMeans


kmeans = KMeans(n_clusters=10, random_state=42)

# Fit the model on features X
kmeans.fit(X)

# Get cluster labels
kmeans_labels = kmeans.labels_

# Display results
print("K-Means model fitted successfully!")
print("Cluster labels shape:", kmeans_labels.shape)
print("First 10 labels:", kmeans_labels[:10])


K-Means model fitted successfully!
Cluster labels shape: (1797,)
First 10 labels: [5 7 7 6 4 9 2 0 8 9]


### Question 9: F1 Score Evaluation for Clustering (5 Marks)

Evaluate the clustering performance using the F1 score. Since K-Means assigns arbitrary cluster labels, you will first need to map each cluster label to the most frequent true label in that cluster.
After mapping the labels, calculate and print the macro-averaged F1 score using `sklearn.metrics.f1_score`.

**Expected Output:** The calculated F1 score of the clustering.

In [ ]:
from sklearn.metrics import f1_score
import numpy as np
from scipy.stats import mode


mapped_labels = np.zeros_like(kmeans_labels)

for cluster in np.unique(kmeans_labels):
    mask = (kmeans_labels == cluster)
    mapped_labels[mask] = mode(y[mask], keepdims=True)[0]


f1 = f1_score(y, mapped_labels, average='macro')

print("F1 Score (Macro):", f1)


F1 Score (Macro): 0.8627854786352394


### Question 10: Confusion Matrix for Clustering (3 Marks)

Generate and display the confusion matrix comparing your mapped cluster labels (from Question 9) to the true labels (`y`). Use `confusion_matrix` from `sklearn.metrics`. This helps evaluate how well your clusters align with the actual digit classes without requiring visual plotting.

**Expected Output:** A 10x10 confusion matrix printed as an array or a Pandas DataFrame.

In [ ]:
from sklearn.metrics import confusion_matrix
import pandas as pd


cm = confusion_matrix(y, mapped_labels)


print("Confusion Matrix:\n", cm)


cm_df = pd.DataFrame(cm,
                     index=[f"True_{i}" for i in range(10)],
                     columns=[f"Pred_{i}" for i in range(10)])

print("\nConfusion Matrix (DataFrame):")
print(cm_df)

Confusion Matrix:
 [[176   0   0   0   2   0   0   0   0   0]
 [  0 130  23   1   0   1   2   0   3  22]
 [  1   6 146  12   0   0   0   2   9   1]
 [  0   0   1 159   0   2   0   7   6   8]
 [  0  13   0   0 159   0   0   5   4   0]
 [  0   0   0   0   2 137   2   0   0  41]
 [  1   3   0   0   0   0 176   0   1   0]
 [  0   0   0   0   0   0   0 169  10   0]
 [  0  14   3   0   0   2   1   2 136  16]
 [  0   1   0   1   3   4   0   8   3 160]]

Confusion Matrix (DataFrame):
        Pred_0  Pred_1  Pred_2  Pred_3  Pred_4  Pred_5  Pred_6  Pred_7  \
True_0     176       0       0       0       2       0       0       0   
True_1       0     130      23       1       0       1       2       0   
True_2       1       6     146      12       0       0       0       2   
True_3       0       0       1     159       0       2       0       7   
True_4       0      13       0       0     159       0       0       5   
True_5       0       0       0       0       2     137       2       0   
T